name: k8s-build
trigger: none

resources:
  repositories:
    - repository: github
      type: github
      endpoint: GitHub
      name: leriksen/min-js-webserver

pool: leiferiksenau-lab3-lappie

stages:
  - stage: build
    displayName: Docker Build and Push
    jobs:
      - job: docker_build
        displayName: Docker Build and Push
        workspace:
          clean: all
        steps:
          - checkout: github
          - script: ls -al
          # - task: Docker@2
          #   displayName: Build and Push
          #   inputs:
          #     command: buildAndPush
          #     repository: leriksen/hreporter
          #     tags: |
          #       $(Build.BuildId)
          #       latest
