name: k8s-build
trigger: none

stages:
  - stage: build
    displayName: Docker Build and Push
    jobs:
      - job: docker_build
        displayName: Docker Build and Push
        workspace:
          clean: all
        steps:
          - checkout: self
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: leriksen/hreporter
              tags: |
                $(Build.BuildId)
                latest
