apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name | lower }}
  namespace: {{ .Values.namespace.name | default "default" | lower }}
  labels:
    app: {{ .Values.application.name | lower }}
spec:
  replicas: {{ .Values.application.replicas | default "1" }}
  selector:
    matchLabels:
      app: {{ .Values.application.name | lower }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name | lower }}
    spec:
      containers:
      - name: {{ .Values.application.name | lower }}
        image: {{ .Values.docker.registry }}/{{ .Values.application.name | lower }}:{{ .Values.application.port | default "latest" }}
        ports:
        - containerPort: {{ .Values.application.port | default "80" }}
