stages:
  - stage: build
    displayName: Docker Build and Push
    jobs:
      - job: docker_build
        displayName: Docker Build and Push
        workspace:
          clean: all
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: AzureCR
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              containerRegistry: AzureCR
              repository: leriksen/min-js-webserver
              addBaseImageData: false
              tags: |
                $(Build.BuildId)
                latest