trigger: none

extends:
  template: ../../devops/templates/microservice.yml
  parameters:
    agentPool: nana-devops
    helmChartPath: ./deployment/min-js-webserver/deployment
    deployBuild:
      - stageName: dev
        displayName: Dev Deployment
        azureServiceConnection: AzureRM
        helmVauleFile: values-dev.yml
        dockerRegistry: nanaacr.azurecr.io/leriksen
        aksCluster: nana
        resourceGroup: nana